version: '3.8'

services:
  mysql-db:
    image: mariadb:latest
    container_name: mysql-container-microapp
    env_file:
      - docker/envs/database.env
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
    command:
      --default-authentication-plugin=mysql_native_password
  spring-app:
    container_name: app-container-microapp
    build:
      context: .
      dockerfile: ./docker/dockerfiles/app.Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
    links:
      - mysql-db
    env_file:
      - docker/envs/app.env
    # restart: on-failure
volumes:
  mariadb-data:
