version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-container
    env_file:
      - docker/envs/database.env
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  spring-app:
    build:
      context: .
      dockerfile: ./docker/dockerfiles/app.Dockerfile
    container_name: spring-container
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
    env_file:
      - docker/envs/app.env

volumes:
  mysql-data:
