spring:
  config:
    activate:
      on-profile: default
  application:
    name: microapp
  datasource:
    url: ${SECRET_DATABASE_URL:jdbc:mysql://localhost}:${SECRET_DB_PORT:3306}/${SECRET_DB_NAME:microapp}?useTimezone=true&serverTimezone=UTC&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    database-platform: org.hibernate.dialect.MySQLDialect
    username: ${SECRET_DB_USERNAME:root}
    password: ${SECRET_DB_PASSWORD:root}
  jpa:
    properties:
      generate-ddl: true
      show-sql: true
      hibernate:
        ddl-auto: create-drop
        dialect: org.hibernate.dialect.MySQLDialect
  flyway:
    locations: "classpath:db/migration"
    baseline-on-migrate: true
    enabled: true
    ignore-missing-migrations: true
    out-of-order: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB
---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: ${SECRET_TEST_DATABASE_URL:jdbc:mysql://localhost}:${SECRET_TEST_DB_PORT:3306}/${SECRET_TEST_DB_NAME:microapp}?useTimezone=true&serverTimezone=UTC&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    database-platform: org.hibernate.dialect.MySQLDialect
    username: ${SECRET_TEST_DB_USERNAME:root}
    password: ${SECRET_TEST_DB_PASSWORD:root}
  jpa:
    properties:
      generate-ddl: true
      show-sql: true
      hibernate:
        ddl-auto: create-drop
        dialect: org.hibernate.dialect.MySQLDialect
  flyway:
    enabled: false
    locations: "classpath:db/migration"
    baseline-on-migrate: true
    ignore-missing-migrations: true
    out-of-order: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB