spring:
  config:
    activate:
      on-profile: default
  application:
    name: microapp
  datasource:
    url: ${SECRET_DATABASE_URL:jdbc:mysql://localhost}:${SECRET_DB_PORT:3306}/${SECRET_DB_NAME:microapp}?useTimezone=true&serverTimezone=UTC&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    database-platform: org.hibernate.dialect.MySQLDialect
    username: ${SECRET_DB_USERNAME:root}
    password: ${SECRET_DB_PASSWORD:root}
  jpa:
    properties:
      generate-ddl: true
      show-sql: true
      hibernate:
        ddl-auto: create-drop
        dialect: org.hibernate.dialect.MySQLDialect
  flyway:
    locations: "classpath:db/migration"
    baseline-on-migrate: true
    enabled: true
    ignore-missing-migrations: true
    out-of-order: true

---

spring:
  config:
    activate:
      on-profile: test
  cache:
    type: none
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;DATABASE_TO_UPPER=false;MODE=MySQL;
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.H2Dialect
    properties.hibernate:
      enable_lazy_load_no_trans: true
